### ISSUE TITLE
Appended Deps Misrendered as Strings

### ISSUE THREAD

**Issue by type1fool** [ash-project/igniter#103]
**Describe the bug**
When `Igniter.Project.Deps.add_dep/3` is called with default opts, a dependency is prepended to the list in `deps/0` in `mix.exs`. When `append: true` is passed, the dependency is appended as a keyword value instead of a tuple.

This appears to be valid - `mix deps.get` works - but it's not the pattern we see in Elixir applications. It also means the generated line would need to be updated to a tuple in order to configure dep options.

**To Reproduce**

```elixir
Igniter.Project.Deps.add_dep(igniter, {:ecto, "~> 3.10"}, append?: true)
```

```elixir
# mix.exs

def deps do
  [
    ...
    {:some_other_dep, "~> 1.0"},
    ecto: "~> 3.10"
  ]
end
```

**Expected behavior**

```elixir
Igniter.Project.Deps.add_dep(igniter, {:ecto, "~> 3.10"}, append?: true)
```

```elixir
# mix.exs

def deps do
  [
    ...
    {:some_other_dep, "~> 1.0"},
    {:ecto, "~> 3.10"}
  ]
end
```

**Additional context**

```elixir
# mix.lock
...
"igniter": {:hex, :igniter, "0.3.63", "ac27c466e6f779cf5f39d200a7d433cd91c8d465277e001661dc9b4680ca9eb3", [:mix], [{:glob_ex, "~> 0.1.7", [hex: :glob_ex, repo: "hexpm", optional: false]}, {:jason, "~> 1.4", [hex: :jason, repo: "hexpm", optional: false]}, {:rewrite, "~> 0.9", [hex: :rewrite, repo: "hexpm", optional: false]}, {:sourceror, "~> 1.4", [hex: :sourceror, repo: "hexpm", optional: false]}, {:spitfire, ">= 0.1.3 and < 1.0.0-0", [hex: :spitfire, repo: "hexpm", optional: false]}], "hexpm", "5e24f71479cfd3575f79a767db51de0b38a633f05107b05d94ef1a54fde9093f"},
...
```

**Comment by zachdaniel** [comment]
Yeah, interesting 🤔 probably when adding a tuple to a list we need to check the format of the element before it.

**Comment by type1fool** [comment]
I can confirm this is fixed, too! 🎉 🎉 Thanks again!
