### ISSUE TITLE
Error When Using --with-args With igniter.new

### ISSUE THREAD

**Issue by thenhawke** [ash-project/igniter#118]
**Describe the bug**
Arguments don't seem to be getting passed to the --with task. When using igniter.new with --with-args argument, I get the error:

```
** (Mix) Could not invoke task "igniter.install": 1 error found!
--with-args : Unknown option
```

**To Reproduce**
`mix igniter.new reproduction --install ash --with phx.new --with-args="--no-live --no-ecto"`

**Expected behavior**
Run through the setup without an error. 

**Runtime**

- Elixir version: 1.17.3
- Erlang version: 
- OS: Linux 
- Igniter version: 0.4.5

**Additional context**
N/A

**Comment by zachdaniel** [comment]
Fixed in the latest installer

**Comment by zachdaniel** [comment]
🤔 strange.

**Comment by zachdaniel** [comment]
Okay, try 0.4.7 :)

**Comment by thenhawke** [comment]
That fixed it, thanks!
