### ISSUE TITLE
ash_phoenix not added to formatter import_deps

### ISSUE THREAD

**Issue by aidalgol** [ash-project/igniter#130]
## Describe the bug
There is no installer for `ash_phoenix`, and nothing else adds `:ash_phoenix` to `import_deps` in `.formatter.exs` when generating an Ash Phoenix project.

## To Reproduce
```
$ mix igniter.new hello --install ash,ash_postgres,ash_phoenix --with phx.new --extend postgres
[snip]
The package `ash_phoenix` had no associated installer task.
```

## Expected behavior
An installer for `ash_phoenix` would add `:ash_phoenix` to the `import_deps` in `.formatter.exs`.

## Runtime
- Erlang/OTP 25 `[erts-13.2.2.10]`
- Elixir 1.17.3
- NixOS 24.11
- `igniter_new-0.4.10`

## Additional context
N/A

**Comment by zachdaniel** [comment]
There is no need for an installer for ash_phoenix and nothing to add to the formatter.

**Comment by aidalgol** [comment]
The [Get Started with Ash and Phoenix](https://hexdocs.pm/ash_phoenix/getting-started-with-ash-and-phoenix.html#add-dependencies) says to do this.

> Add :ash, :ash_phoenix, and :ash_postgres to your .formatter.exs file.

Is this incorrect?

**Comment by zachdaniel** [comment]
Yes, it's incorrect. Mind PRing the removal of ash_phoenix from that list?

**Comment by aidalgol** [comment]
Submitted https://github.com/ash-project/ash_phoenix/pull/262
