### ISSUE TITLE
Avoid hexadecimal integer conversions (0x250000 -> 2_424_832)

### ISSUE THREAD

**Issue by petermm** [ash-project/igniter#164]
**Describe the bug**
If one uses a hexadecimal integer eg 0x250000 it's outputted with it's integer value eg. 2_424_832

**To Reproduce**
Use a hexadecimal integer anywhere eg:
``` Elixir
    Igniter.update_elixir_file(igniter, "mix.exs", fn zipper ->
       with {:ok, zipper} <- Igniter.Code.Function.move_to_def(zipper, :project, 0),
            {:ok, zipper} <-
              Igniter.Code.Keyword.put_in_keyword(
                zipper,
                [:atomvm],
                start: Igniter.Project.Module.module_name_prefix(igniter),
                esp32_flash_offset: 0x250000,
              ) do
         {:ok, zipper}
       end
     end)
```

results in:

``` Elixir 
atomvm: [start: MyProject, flash_offset: 2_424_832]
```

**Expected behavior**
Clearly they are functionally the same, but the hexadecimal `0x250000` has a special human/documentation meaning.

**Additional context**
I imagine this might be difficult to solve.

**Comment by zachdaniel** [comment]
I believe if you pass in the sorcerer quoted form that this would work. Try `Sourceror.parse_string!("0x250000"")`

**Comment by zachdaniel** [comment]
Passing in just the value it's impossible (not just hard) for us to know what format it was initially given in.

**Comment by petermm** [comment]
> I believe if you pass in the sorcerer quoted form that this would work. Try `Sourceror.parse_string!("0x250000"")`

confirmed working🎉❤️
