### ISSUE TITLE
Message "The package <package> had no associated installer task." is confusing

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/igniter#169]
**Is your feature request related to a problem? Please describe.**
This has come up a couple of times now, eg. [here](https://elixirforum.com/t/clean-install-from-docs-the-package-ash-phoenix-had-no-associated-installer-task/67838). People are getting the impression that this message means that something went wrong, and something needs to be fixed before proceeding.

**Describe the solution you'd like**

The message could be removed entirely I think. 

Alternatively, a message *after* that could very clearly tell the user (with green success text?) that the install was a success.

Do we have a way that install script writers can add output messages of different levels, eg. info, warning, etc.? That may also be useful long-term. To make something like:

<img width="646" alt="Screenshot 2024-12-17 at 6 03 19 PM" src="https://github.com/user-attachments/assets/e9a4c778-4278-40f1-9a58-9690edb67cd1" />

**Comment by zachallaun** [comment]
👍 Agreed that this message should be reframed or removed. Right now, there's an API for adding errors, warnings, and notices (which I believe are akin to "info" in your examples). Here's what it would look like as a notice:

![image](https://github.com/user-attachments/assets/77959f18-a103-4c15-a400-2a1905922c0e)

Do you think that's enough to make it non-threatening? Maybe a rephrasing as well? "Package 'ash_phoenix' added (no associated installer task)." or something

**Comment by sevenseacat** [comment]
Having it marked as a notice like that would be good, maybe with a wording tweak like "...no associated installer task, skipping..." and a clear success message after that.

**Comment by zachdaniel** [comment]
I'm thinking we should just remove it. If there is no installer task, then adding it to the deps counts as installng it? I guess it Is useful to know actually. It signals you probably need to go read a setup guide.

**Comment by zachdaniel** [comment]
The thing that makes it kind of strange is that ash_phoenix, requires no setup. Maybe we need some way to signal that?

**Comment by sevenseacat** [comment]
We could signal it by adding an empty installer task, right? For cases where we know there's nothing we need to do.

**Comment by zachallaun** [comment]
> The thing that makes it kind of strange is that ash_phoenix, requires no setup. Maybe we need some way to signal that?

Most packages without installers won't be using Igniter at all, so they won't be able to signal anything, and it shouldn't (imo) be the responsibility of packages adding them to know whether they require additional setup or not. E.g. maybe a task in ash adds ash_phoenix, but it should be the one to declare "ash_phoenix does or doesn't require some additional setup".

I'm on the side of just being really explicit about it:

> Notice: Package 'ash_phoenix' was added without an installer task. If additional setup is necessary, please check the 'ash_phoenix' docs.

If we wanted, we could even add a link to hexdocs.pm for that package and version.

**Comment by zachallaun** [comment]
Maybe something like

> Notice: Package 'ash_phoenix' was added without an installer task. You can check the 'ash_phoenix' docs to see if additional setup is necessary: <LINK>

**Comment by zachdaniel** [comment]
For now, I'm just removing it :) Lets keep it simple. 99% of packages don't have igniter installers.
