### ISSUE TITLE
Prevent creating .igniter and add all custom pathes in it

### ISSUE THREAD

**Issue by shahryarjb** [ash-project/igniter#173]
Hi. As we discussed on Discord, I was supposed to prepare an example for this section.

The main issue is that I want to use dont_move_file_pattern or any other function that allows the user to define their custom path. However, imagine if I have 80 graphical components created with Igniter — all the paths would be placed in a single configuration file.

I’ve included an example below.
```
➜  mishka git:(master) ✗ mix mishka.ui.gen.component divider --module Foo.Boo
      .-.
     /'v'\
    (/   \)
    =="="==
  Mishka.tools

Igniter:

Create: .igniter.exs

1  |# This is a configuration file for igniter.
2  |# For option documentation, see https://hexdocs.pm/igniter/Igniter.Project.IgniterConfig.html
3  |# To keep it up to date, use `mix igniter.setup`
4  |[
5  |  module_location: :outside_matching_folder,
6  |  extensions: [{Igniter.Extensions.Phoenix, []}],
7  |  source_folders: ["lib", "test/support"],
8  |  dont_move_files: [~r/lib\/mishka_web\/components\/boo.ex/, ~r"lib/mix"]
9  |]
10 |
```

In this section, I encounter two issues. First, since my program already has its own configuration file, I don’t want to add another configuration. I only need to set up a custom path as proper_location and place my files there.

Second, if I’m unable to use this approach, some projects with incorrect naming conventions unfortunately won’t be installable through my CLI.

Below, I’ve included the code snippet I’m using.

```elixir
proper_location = Module.concat([
              Igniter.Libs.Phoenix.web_module(igniter),
              "components",
              atom_to_module(custom_module, :last)
            ])
            |> then(&Igniter.Project.Module.proper_location(igniter, &1))

igniter
|> Igniter.Project.IgniterConfig.dont_move_file_pattern(~r/#{proper_location}/)
|> Igniter.compose_task("igniter.add_extension", ["phoenix"])
```

You can try it from this branch: https://github.com/mishka-group/mishka_chelekom/tree/fix-custom-cli-path
And please use this command `mix mishka.ui.gen.component divider --module AABB.Boo`

---

- Elixir version 1.18
- Erlang version 27
- MacOs last version
- Igniter version 0.5.0

Thank you in advance

## Ref
- https://discord.com/channels/711271361523351632/1253324141491261472/1319686219944427610

**Comment by zachdaniel** [comment]
Hey @shahryarjb as a temporary workaround, what you could do is modify the value in 

`igniter.assigns[:igniter_exs]` without editing the underlying igniter.exs file. Alternatively, you could update the igniter.exs file and then discard any changes by removing it from the rewrite. Could you try those and let me know how it goes?

**Comment by zachdaniel** [comment]
Try it this way instead of using `IgniterConfig`

```elixir
your_dont_move_file = ".....ex"

igniter
|> Map.update!(:assigns, fn assigns -> 
  assigns
  |> Keyword.put_new(:igniter_exs, [])
  |> Keyword.update!(:igniter_exs, fn igniter_exs ->
    Keyword.update(igniter_exs, :dont_move_files, [your_dont_move_files], &[your_dont_move_file | &1])
  end)
end)
```

The idea is to temporarily modify the config without updating the file.

**Comment by zachdaniel** [comment]
We do need to figure out some general fix to this though, like we probably shouldn't move files at all if it wouldn't be in an existing top/second level folder? Or if there is a matching folder w/ different casing?

You could even just do my example once with a regex that matches anything to tell us not to move any files

**Comment by shahryarjb** [comment]
> Try it this way instead of using `IgniterConfig`
> 
> ```elixir
> your_dont_move_file = ".....ex"
> 
> igniter
> |> Map.update!(:assigns, fn assigns -> 
>   assigns
>   |> Keyword.put_new(:igniter_exs, [])
>   |> Keyword.update!(:igniter_exs, fn igniter_exs ->
>     Keyword.update(igniter_exs, :dont_move_files, [your_dont_move_files], &[your_dont_move_file | &1])
>   end)
> end)
> ```
> 
> The idea is to temporarily modify the config without updating the file.

I used this, instead of Keyword list, and it works I think, because it does not create `.igniter.exs` file anymore and I deleted the `Igniter.compose_task("igniter.add_extension", ["phoenix"])`, it creates config file like the `dont_move_files`

```
template.igniter
|> Map.update!(:assigns, fn assigns ->
    assigns
    |> Map.put_new(:igniter_exs, [])
    |> Map.update!(:igniter_exs, fn igniter_exs ->
    Keyword.update(
        igniter_exs,
        :dont_move_files,
        [proper_location],
        &[proper_location | &1]
    )
    end)
end)
```


> We do need to figure out some general fix to this though, like we probably shouldn't move files at all if it wouldn't be in an existing top/second level folder? Or if there is a matching folder w/ different casing?

I think, similar to Mnesia, there should be a "dirty" solution that allows the user-programmer to specify their own path, eliminating the need for anything else. Additionally, since the programmer is defining the path, better error control will also be their responsibility.


I test it more and will send a message if I have another problem

For now thank you in advance

**Comment by zachdaniel** [comment]
> I think, similar to Mnesia, there should be a "dirty" solution that allows the user-programmer to specify their own path, eliminating the need for anything else. Additionally, since the programmer is defining the path, better error control will also be their responsibility.

I think what we'd do is add an assign in `igniter.assigns[:private]` called `dont_move_files`, and when you are creating a file you can specify an option and that file won't be moved.

PRs welcome to add that 🙇 

With that said, we should still make it smarter to detect that the path we want to put it in exists w/ different casing, so that others don't have to specify this option if they don't want to.
