### ISSUE TITLE
v0.5.2 can't install other packages (e.g. mix igniter.install ash_postgres)

### ISSUE THREAD

**Issue by jaeyson** [ash-project/igniter#175]
**Describe the bug**

After I installed `igniter` by adding it in mix.exs, running `mix igniter.install ash` went fine.

The problem is when I add another dependency by running i.e. `mix igniter.install ash_postgres` and it throws:

```elixir
** (UndefinedFunctionError) function Installer.Lib.Private.SharedUtils.igniter_version/0 is undefined (module Installer.Lib.Private.SharedUtils is not available)
    (igniter 0.5.2) Installer.Lib.Private.SharedUtils.igniter_version()
    (igniter 0.5.2) lib/mix/tasks/igniter.install.ex:86: Mix.Tasks.Igniter.Install.add_igniter_dep/1
    (igniter 0.5.2) lib/mix/tasks/igniter.install.ex:37: Mix.Tasks.Igniter.Install.run/1
    (mix 1.18.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.18.1) lib/mix/cli.ex:107: Mix.CLI.run_task/2
    /Users/jaeyson/.asdf/installs/elixir/1.18.1-otp-27/bin/mix:2: (file)
```

**To Reproduce**

1. `mix local.hex`
2. `mix archive.install hex phx_new` (v1.7.18)
3. `mix archive.install hex igniter_new` (v0.5.2)
4. `mix phx.new app_name --binary-id`
5. added `{:igniter, "~> 0.5", only: [:dev, :test]}` in `mix.exs`
6. `mix deps.get && mix compile`
7. `mix igniter.install ash` (v3.4.49)
8. `mix igniter.install ash_postgres` <-- error occurred

**Expected behavior**

I'm expecting the igniter interactive shell to run and i.e. ash_postgres will continue to install and ask interactive question(s).

\*\* Runtime

- Elixir version: v1.18.1-otp-27 (asdf)
- Erlang version: 27.2 (asdf)
- OS: Mac M1 Sonoma 14.2.1
- Igniter version: v0.5.2

Related extension versions:
- Phoenix v1.7.18
- Ash framework v3.4.49
- [Asdf](https://asdf-vm.com) v0.13.1-0586b37

**Additional context**

~Downgrading it to v0.5.1 `{:igniter, "0.5.1", only: [:dev, :test]}` somehow solved my problem. Interactive shell also worked ("What is the minimum PostgreSQL version you will be using?")~

**Comment by jaeyson** [comment]
`0.5.2` is working fine: what I did was not actually running `mix archive.install hex igniter_new` and instead add it via mix.exs.

After mix deps.get and `mix igniter.install`:
```elixir
** (ArgumentError) must provide at least one package to install
    (igniter 0.5.2) installer/lib/private/shared_utils.ex:49: Installer.Lib.Private.SharedUtils.install/1
    (mix 1.18.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.18.1) lib/mix/cli.ex:107: Mix.CLI.run_task/2
    /Users/jaeyson/.asdf/installs/elixir/1.18.1-otp-27/bin/mix:2: (file)
```

> Even if it doesn’t have igniter in that projects deps
> If you remove the archive and don’t add it back in
https://discord.com/channels/711271361523351632/1069610909296766998/1321486115080769536

Also installed e.g. ash_postgres, ash_phoenix, etc. and went fine. Thanks for your help!!! :pray_tone4: :pray_tone4: :pray_tone4:

**Comment by user20230119** [comment]
Were you unable to install other packages with `mix igniter.install`?

I have the same issue with `mix igniter.install exinertia`

https://github.com/nordbeam/exinertia/issues/2

**Comment by zachdaniel** [comment]
Is your archive up to date? `mix archive.install hex igniter_new`? Is igniter up to date in the project in question?

**Comment by user20230119** [comment]
I have `igniter_new 0.5.23`.

```
> mix archive.install hex igniter_new
Resolving Hex dependencies...
Resolution completed in 0.014s
New:
  igniter_new 0.5.23
* Getting igniter_new (Hex package)
All dependencies are up to date
Compiling 5 files (.ex)
Generated igniter_new app
Generated archive "igniter_new-0.5.23.ez" with MIX_ENV=prod
Found existing entry: [...]/.mix/archives/igniter_new-0.5.23
Are you sure you want to replace it with "igniter_new-0.5.23.ez"? [Yn]
* creating [...]/.mix/archives/igniter_new-0.5.23
```

**Comment by zachdaniel** [comment]
And in what is the locked version of igniter in your project?

**Comment by zachdaniel** [comment]
Looks like 0.5.35. I will try to reproduce.

**Comment by zachdaniel** [comment]
Are you doing `cd exinertia_sample` after `mix phx.new exinertia_sample`?

**Comment by user20230119** [comment]
I did `cd exinertia_sample`. I updated the steps above.

**Comment by zachdaniel** [comment]
What is the output of `mix archive`?

**Comment by user20230119** [comment]
```
> mix archive
* hex-2.1.1
* igniter-0.3.60
* igniter_new-0.5.23
* phx_new-1.7.18
Archives installed at: [...]/.mix/archives
```

**Comment by user20230119** [comment]
`mix igniter.install exinertia` works after I did `mix archive.uninstall igniter`.

**Comment by zachdaniel** [comment]
I believe we have a check for this now in new versions of igniter that will raise if you have it installed as an archive

**Comment by jaeyson** [comment]
did you try adding the igniter in mix.exs instead of installing it like mix archive.install hex igniter_new? i tried doing it in clean slate and it seems working fine on my end.
