### ISSUE TITLE
Support running non-installation Igniter tasks from the CLI

### ISSUE THREAD

**Issue by ibarakaiev** [ash-project/igniter#20]
**Is your feature request related to a problem? Please describe.**
Some helper tasks might be implemented with Igniter tasks instead of regular Mix tasks, and it currently seems impossible to run something like `mix igniter.run {task_name}`. For example, `:ash_money` might have an Igniter install task and a `add_to_ash_postgres` Igniter task. It would currently be impossible to run the latter.

**Describe the solution you'd like**
Support `mix igniter.run {task_name}` or something like that.

**Comment by zachdaniel** [comment]
I'm not sure I understand the issue. Any igniter task can be run on its own as a regular task. i.e `mix {task_name}`

**Comment by zachdaniel** [comment]
They are both `igniter` tasks *and* their own `mix` tasks.

**Comment by ibarakaiev** [comment]
Got it—I mistakenly thought that the `run` function for Igniter tasks expects an existing igniter, but I just saw that it's being created there. Then the issue doesn't make sense, so closing!
