### ISSUE TITLE
Check for and warn on uncommitted git changes when running an igniter task.

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/igniter#26]
We want to protect users from getting into bad states, so we should warn them about uncommitted changes.

**Comment by girishramnani** [comment]
I was thinking of doing this task?
What if I ran `git status -s --porcelain` and if that returns any output then we can show a warning? Obviously I will check if the folder is a valid git repo before running this command.
Does this approach work?

**Comment by zachdaniel** [comment]
That sounds like a good approach to me 👍

**Comment by zachdaniel** [comment]
We will want to be defensive, and check for access to the `git` executable as well. If it is not a git repository, or the `git` executable could not be found, we should warn that we were unable to check project status and require confirmation, I think. If there are changes, we should stop and tell them that there are uncommitted changes, and require that they confirm before continuing.

**Comment by girishramnani** [comment]
makes sense

**Comment by zachdaniel** [comment]
Completed in 84e20aa3331269c0cd9b076c7166d3dda939c802
