### ISSUE TITLE
Support more complex add dep configuration, e.g. `:only`

### ISSUE THREAD

**Issue by zachallaun** [ash-project/igniter#35]
**Is your feature request related to a problem? Please describe.**
I was playing around with building an Igniter installer for a library of mine, but found that the high-level `Project.Deps` utils do not support adding deps with more complex configuration, e.g. `{:mneme, ">= 0.0.0", only: :test}`

**Describe the solution you'd like**
Instead of accepting the package name and version as separate arguments, I'd propose that a dep tuple be passed in and inserted or used to replace existing dep tuples based on a matching first argument.

**Describe alternatives you've considered**
Unless I'm mistaken, the only alternative at the moment is to use much lower-level tools to modify the deps list yourself.

**Comment by zachallaun** [comment]
You're a beast

**Comment by zachdaniel** [comment]
🙇 😆
