### ISSUE TITLE
Possible to parse arguments to an igniter so that options can come first?

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/igniter#60]
**Is your feature request related to a problem? Please describe.**

I want to do create a mix alias pre-populated with preferred options to an Igniter, eg.

```elixir
def aliases do 
  [
    "myapp.gen.resource": ["ash.gen.resource -e postgres -u id"]
  ]
end
```

But then trying to use the alias errors out:

```
$ mix myapp.gen.resource Cat.Food.Dry
** (ArgumentError) expected an Elixir module, got: Elixir
    (elixir 1.17.2) lib/module.ex:1747: Module.split/2
    (igniter 0.3.9) lib/igniter/code/module.ex:381: Igniter.Code.Module.do_proper_location/2
    (ash 3.2.6) lib/mix/tasks/gen/ash.gen.domain.ex:18: Mix.Tasks.Ash.Gen.Domain.igniter/2
```

This is the exact same error you get when you provide options to the original non-aliased Igniter without providing a module name.

The error is specific to the Ash igniters for domains/resources, due to how it parses options - it pulls the important parts from the front of the `argv` list - but I feel that that required argument should be able to be extracted from the args like the other CSV options are.

In somewhere like here - https://github.com/ash-project/ash/blob/main/lib/mix/tasks/gen/ash.gen.resource.ex#L78-L86

Does this seem reasonable?

**Describe the solution you'd like**

Something in Igniter to allow specifying required named (positional?) arguments, so after parsing them you could access eg. `options[:resource]` to read what is currently being read from the front of the args to the mix task.

**Comment by zachdaniel** [comment]
positional arguments support has been added to main
