### ISSUE TITLE
Use provided module name in created application file

### ISSUE THREAD

**Issue by sinisijacob** [ash-project/igniter#78]
I'm attempting to use the Project.Application.create_app() function to create a new app, but it hard codes the Supervisor name to Foo.Supervisor.

I would like the Project.Application.create_application_file() to use the correct module name when filling in the opt name.

I have considered going in and altering the source after creating the file, but it seems like this shouldn't be Foo if the application create knows the correct module name.

For example

```elixir
opts = [strategy: :one_for_one, name: Foo.Supervisor]
```
becomes something like
```elixir
opts = [strategy: :one_for_one, name: #{inspect(Module.module_name_prefix(application)}.Supervisor]
```

**Comment by zachdaniel** [comment]
Thats....such a silly mistake, sorry 😢. I will fix.
