### ISSUE TITLE
Helpdesk.Repo added twice when run with `--with phx.new --example`

### ISSUE THREAD

**Issue by axelbdt** [ash-project/igniter#80]
**Describe the bug**
A slight error in the codegen adds Helpdesk.Repo in the application children twice and prevent the launch.

**To Reproduce**
When running the "full enchilada" command from the getting started :
```shell
mix archive.install hex phx_new

mix igniter.new helpdesk \
  --install ash,ash_postgres \
  --with phx.new \
  --extend postgres \
  --example
```
Then `mix phx.server`.

You get the following error :
```
** (Mix) Could not start application helpdesk: Helpdesk.Application.start(:normal, []) returned an error: bad child specification, more than one child specification has the id: Helpdesk.Repo.
```

The project won't launch because `lib/helpdesk/application.ex` has Helpdesk.Repo appear two times in its children (lines 11 and 13) :
```elixir
  def start(_type, _args) do
    children = [
      Helpdesk.Repo,
      HelpdeskWeb.Telemetry,
      Helpdesk.Repo,
```

Had a look in the igniter code to offer a fix, but I'm in over my head, sorry!

** Runtime **

- Elixir 1.17.2
- Erlang 27.0.1
- OS PopOS 22.04
- Igniter version 0.3.5 (I think, just got it)

**Comment by zachdaniel** [comment]
Fixed in `0.3.34`
