### ISSUE TITLE
`mix igniter.new app_name --with=phx.new` adds Igniter to mix.exs but does not install it

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/igniter#88]
**Describe the bug**

Not sure if this could be considered a bug, but worth a mention I think.

When generating a new app using `mix igniter.new app_name --with=phx.new`, and accepting to fetch and install dependencies, this seems to happen before Igniter is added to `mix.exs`, so it's not installed.

Meaning, as soon as you generate a new app, you then have to `cd` into the app folder and run `mix deps.get` again to actually fetch and install Igniter and its dependencies. It's kind of weird.

**To Reproduce**

```
$ mix archive.install hex igniter_new
  <installs igniter_new 0.3.5>

$ mix igniter.new tunez --with=phx.new
  <creates a bunch of stuff>
  Fetch and install dependencies? [Yn] y
* running mix deps.get
* running mix assets.setup
* running mix deps.compile

$ cd tunez

$ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.205s
New:
  glob_ex 0.1.8
  igniter 0.3.38
  rewrite 0.10.5
  sourceror 1.6.0
  spitfire 0.1.3
Unchanged:
  ...
```

**Expected behavior**

After deps are installed, the app should be good to go so I can `cd` in and run `mix phx.server` and have a running app.

**Runtime**

- Elixir version 1.17.2-otp-27
- Erlang version 27.0.1
- OS macOS Sonoma
- Igniter version 0.3.38
- Igniter_new version 0.3.5
- phx_new version 1.7.14

**Comment by zachdaniel** [comment]
fixed in latest installer. An unfortunate end result here is that we're ignoring if the user says `n` I don't want to install dependencies now, but from the perspective of the tool you can put anything in `--with`. We don't know what prompts it gives you or other things it does.
