### ISSUE TITLE
:rewrite not getting appropriately filled in in Igniter.Mix.Task.__using__()

### ISSUE THREAD

**Issue by sinisijacob** [ash-project/igniter#92]
When running an igniter I get the following error:
`** (FunctionClauseError) no function clause matching in Application.ensure_all_started/2    
    
    The following arguments were given to Application.ensure_all_started/2:
    
        # 1
        [:rewrite]
    
        # 2
        :temporary
    
    Attempted function clauses (showing 1 out of 1):
    
        def ensure_all_started(app, type) when is_atom(app)
    
    (elixir 1.14.0) lib/application.ex:848: Application.ensure_all_started/2
    (app_assembler 0.1.0) lib/mix/tasks/foo.gen.bar.ex:2: Mix.Tasks.Foo.Gen.Bar.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2`

My igniter looks like this:
`defmodule Mix.Tasks.Foo.Gen.Bar do
  use Igniter.Mix.Task

  def igniter(igniter, _argv) do
    igniter
      |> Igniter.add_task("phx.gen.auth", ["Accounts", "User", "users"])
  end
end`

I would expect the [:rewrite] to get replaced with the app, but that doesn't seem to be happening.

\*\* Runtime

- Elixir 1.14.0 (compiled with Erlang/OTP 24)
- Erlang/OTP 26 [erts-14.2.5.2]
- OS: Ubuntu
- Igniter 0.3.40

Not sure if this is a bug with Igniter per se, might just be something I'm doing wrong. Looking through the Igniter.Mix.Task.__using__() def I can't seem to find where it should be updating that value and why it isn't in my particular case.

**Comment by zachdaniel** [comment]
Fixed in `0.3.45`. I will also publish a new version of `mix igniter.new`

**Comment by zachdaniel** [comment]
Done.
