### ISSUE TITLE
Small markdown bug in documentation of 

### ISSUE THREAD

**Issue by wintermeyer** [ash-project/igniter#97]
https://hexdocs.pm/igniter_new/Mix.Tasks.Igniter.New.html displays the following which has the wrong indentation/formatting (see red rectangle):

<img width="916" alt="Bildschirmfoto 2024-10-12 um 10 35 42" src="https://github.com/user-attachments/assets/d0707d0c-1478-406e-8df5-5ca7b760b7a0">

See https://hexdocs.pm/igniter_new/Mix.Tasks.Igniter.New.html

**Comment by zachdaniel** [comment]
Thanks for pointing this out, pushed a fix to the docs 🙇
